### ISSUE TITLE
Default to single-package rather than workspace?

### ISSUE THREAD

**Issue by g-re-g** [leptos-rs/cargo-leptos#160]
If you run `cargo leptos watch` with a barebones app, just a `main.rs`, `lib.rs` and this `cargo.toml`:
```toml
[package]
name = "cl_test"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
leptos = { version = "0.4.3" }
```

It won't run with the following error:
```
Caused by:
    Please define leptos projects in the workspace Cargo.toml sections [[workspace.metadata.leptos]]
```

This is because of some code in cargo-leptos that is essentially defaulting to workspace mode. What I, and possibly other folks looking to build a cargo-leptos compatible app from scratch, am looking to do is actually build with a single-package setup. This is easily fixed by creating an empty `[package.metadata.leptos]` section. But this is non obvious for a couple reasons:

* All of the parameters for this section are optional
* The error message mentions workspaces and I don't have any set up.

Perhaps it would be either better to default to single package mode or perhaps to have a more verbose error message.
