### ISSUE TITLE
When using a plain css style sheet, lightning should be configured to bundle in any @import style sheets

### ISSUE THREAD

**Issue by DanielJoyce** [leptos-rs/cargo-leptos#238]
Given the following:

```css
@import "../generated/leptonic/leptonic-themes";

body {
	font-family: sans-serif;
	text-align: center;
}

:root {
	--brand-color: green;
}
```

If it is named as main.scss then sass resolves the import and it gets bundled as one file
`style-file = "style/main.scss"`

If it is named as main.css, then the import is not bundled by the current lightning config. 
`style-file = "style/main.css"`
