### ISSUE TITLE
Cargo leptos builds 'fail' when using config.toml

### ISSUE THREAD

**Issue by tadghh** [leptos-rs/cargo-leptos#279]
Here is a config file for example, it should be placed in .cargo

```toml
[unstable]
build-std = ["std", "panic_abort", "core", "alloc"]
build-std-features = ["panic_immediate_abort"]
[build]
target = "x86_64-unknown-linux-musl"
target-dir = "target"
rustflags = ["--cfg=has_std","-C", "panic=abort"]

```

This will result in the project being built in 'target/x86_64-unknown-linux-musl' leading to the following error
```
 Cargo finished cargo build --package=tadgh-blog-leptos --bin=tadgh-blog-leptos --no-default-features --features=ssr --release
311.0 Error: at `/home/runner/work/cargo-leptos/cargo-leptos/src/compile/server.rs:39:22`
311.0
311.0 Caused by:
311.0     0: at `/home/runner/work/cargo-leptos/cargo-leptos/src/service/site.rs:117:44`
311.0     1: Could not read "target/release/project-name-here" at `/home/runner/work/cargo-leptos/cargo-leptos/src/ext/fs.rs:44:10`
311.0     2: No such file or directory (os error 2)
```
