### ISSUE TITLE
next cargo-leptos (rewrite branch) config file

### ISSUE THREAD

**Issue by luoxiaozero** [leptos-rs/cargo-leptos#407]
Organize config and commands for discussion.

**Leptos.toml**

```toml
cargo-leptos-version = "*"
release = false

# Custom commands, e.g. `leptos run dev` `leptos run build-release`
[commands]
dev = "leptos serve --config leptos.dev.toml"
build-release = "leptos serve --config leptos.release.toml"

[server]
# Specify which IP addresses the server should listen on.
host = "localhost"
# Specify server port.
port = 3000
# Automatically open the app in the browser on server start.
open = false
# File system watcher
default-watch = true
watch = ["Cargo.toml", "docs/**/*.md"]

# Configure custom proxy rules for the dev server.
[[server.proxy]]
match = "/api"
target = "http://localhost:8080"
# Changes the origin of the host header to the target URL.
change-origin = false
ws = false

[build]
# The name used by wasm-bindgen/cargo-leptos for the JS/WASM bundle. Defaults to the crate name
output-name = ""
# The site root folder is where cargo-leptos generate all output. WARNING: all content of this folder will be erased on a rebuild. Use it in your server setup.
output-dir = "target/site"
# The output-dir relative folder where all compiled output (JS, WASM and CSS) is written
assets-dir = "assets"
# Copy to the root directory of output-dir and are always served or copied as-is without transform.
public-dir = "public"

[build.csr]
lib = true
args = []
target = "wasm32-unknown-unknown"
default-features = false
features = ["csr"]

[build.ssr]
lib = false
args = []
default-features = false
features = ["ssr"]

[build.hydrate]
lib = true
args = []
target = "wasm32-unknown-unknown"
default-features = false
features = ["hydrate"]
```

**commands**

```
leptos new --template leptos-rs/start-axum
leptos new --template https://github.com/leptos-rs/start-axum
leptos new --template DioxusLabs/dioxus-template --subtemplate Desktop
leptos new --template https://github.com/DioxusLabs/dioxus-template --subtemplate Desktop

leptos serve csr
leptos serve ssr
leptos serve ssr --no-hydrate

leptos build csr
leptos build ssr
leptos build ssr --no-hydrate
leptos build hydrate
```
