### ISSUE TITLE
[enhancement] Ability to add CLI flags to server and library `cargo` invocations

### ISSUE THREAD

**Issue by ActuallyHappening** [leptos-rs/cargo-leptos#423]
I want to change the profile that my `wasm` bundle is compiled under during development, because I want it's dependencies to take up less size so that `wasm-bindgen` takes less than 4 seconds as it does currently.
Ideally there would be two additional configuration options: `lib-cargo-flags: ["--profille","wasm-dev"]` and `bin-cargo-flags: Vec<String>` as an example of two names.
If I implemented this, would there be any objections to this design?

**Comment by ActuallyHappening** [comment]
This would also allow be to opt into using `cranelift` for incremental server compilation

**Comment by gbj** [comment]
The following currently exist:
```toml
# The profile to use for the lib target when compiling for debug
#
# Optional. Defaults to "debug".
lib-profile-dev = "my-debug-profile"

# The profile to use for the bin target when compiling for debug
#
# Optional. Defaults to "debug".
bin-profile-dev = "my-debug-profile"

# Pass additional parameters to the cargo process compiling to WASM
#
# Optional. No default
lib-cargo-args = ["--timings"]

# Pass additional parameters to the cargo process to build the server
#
# Optional. No default
bin-cargo-args = ["--timings"]
```

`lib-profile-dev` should allow you to do what you're asking for (set the profile during dev mode), the other ones allow passing arbitrary arguments to cargo.

Could you clarify what you want to be able to do that doesn't fall into one of those? I'm not sure I understand.
