### ISSUE TITLE
Using entry point under `src/bin` causes compilation error

### ISSUE THREAD

**Issue by dsgallups** [leptos-rs/cargo-leptos#459]
**Describe the bug**
When running the app from a `bin` module, `cargo leptos watch` fails to compile, even after provided the bin name in the `[package.metadata.leptos]` section (`bin-target = "name"`) after `cargo clean`

**Leptos Dependencies**

Please copy and paste the Leptos dependencies and features from your `Cargo.toml`.
```
leptos = { version = "0.7.0", features = ["nightly"] }
leptos_router = { version = "0.7.0", features = ["nightly"] }
```

**To Reproduce**
Run the starter leptos project and move `main.rs` to `bin/app.rs`. Provide this binary name in the leptos metadata. 
Run `cargo clean`. Project seems to work using incremental compilation.

The program should fail to compile with the following error:

```console
Error:
   0: at `/home/dan/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/cargo-leptos-0.2.29/src/compile/server.rs:40:22`
   1: at `/home/dan/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/cargo-leptos-0.2.29/src/service/site.rs:115:44`
   2: Could not read "target/debug/danielgallups" at `/home/adamime/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/cargo-leptos-0.2.29/src/ext/fs.rs:44:10`
   3: No such file or directory (os error 2)

Location:
   /home/dan/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/cargo-leptos-0.2.29/src/ext/fs.rs:44
```

**Comment by DylanRJohnston** [comment]
There's an undocumented configuration option which solves this issue https://github.com/leptos-rs/cargo-leptos/blob/main/src/config/project.rs#L282

**Comment by DylanRJohnston** [comment]
From my config
```toml
[[workspace.metadata.leptos]]
name = "deep-space-derby"

bin-package = "app"
bin-target = "server"
bin-default-features = false
bin-exe-name = "server"
bin-features = ["ssr", "native"]
```
