### ISSUE TITLE
Bug: Leptos Prints Serving at http://127.0.0.1:3000 Even Without site-addr in Config

### ISSUE THREAD

**Issue by Ritzier** [leptos-rs/cargo-leptos#512]
When I remove the site-addr field from my Leptos project's `Cargo.toml` configuration and specify the server address in
my own config file, Leptos still prints:

```bash
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.21s
       Cargo finished cargo build --package=one --lib --target-dir=/home/ritzier/Templates/one/target/front --target=wasm32-unknown-unknown --no-default-features --features=hydrate
       Front generating JS/WASM with wasm-bindgen
    Finished generating JS/WASM for front in 580.851401ms
    Tailwind finished tailwindcss --input style/tailwind.css --output /home/ritzier/Templates/one/target/tmp/tailwind.css
   Compiling one v0.1.0 (/home/ritzier/Templates/one)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 2.74s
       Cargo finished cargo build --package=one --bin=one --no-default-features --features=ssr
     Serving at http://127.0.0.1:3000
    listening on http://127.0.0.1:8080
```

I'm expected it won't print the serving when `site-addr` is not setup

## Full code:

`main.rs`:

```main.rs
#[cfg(feature = "ssr")]
#[tokio::main]
async fn main() {
    use std::net::{IpAddr, Ipv4Addr, SocketAddr};

    use axum::Router;
    use leptos::logging::log;
    use leptos::prelude::*;
    use leptos_axum::{generate_route_list, LeptosRoutes};
    use one::app::*;

    let conf = get_configuration(None).unwrap();
    let addr = SocketAddr::new(IpAddr::V4(Ipv4Addr::new(127, 0, 0, 1)), 8080);
    let leptos_options = conf.leptos_options;
    // Generate the list of routes in your Leptos App
    let routes = generate_route_list(App);

    let app = Router::new()
        .leptos_routes(&leptos_options, routes, {
            let leptos_options = leptos_options.clone();
            move || shell(leptos_options.clone())
        })
        .fallback(leptos_axum::file_and_error_handler(shell))
        .with_state(leptos_options);

    // run our app with hyper
    // `axum::Server` is a re-export of `hyper::Server`
    log!("listening on http://{}", &addr);
    let listener = tokio::net::TcpListener::bind(&addr).await.unwrap();
    axum::serve(listener, app.into_make_service())
        .await
        .unwrap();
}
```

Leptos config part in `Cargo.toml`:

```toml
[package.metadata.leptos]
output-name = "leptos_project"

style-file = "style/main.scss"
tailwind-input-file = "style/tailwind.css"

site-root = "target/site"
site-pkg-dir = "pkg"
assets-dir = "public"

end2end-cmd = "npx playwright test"
end2end-dir = "end2end"

browserquery = "defaults"
env = "DEV"
watch = false

bin-features = ["ssr"]
bin-default-features = false
lib-features = ["hydrate"]
lib-default-features = false
lib-profile-release = "wasm-release"
```
