### ISSUE TITLE
Separate profiles for front and server

### ISSUE THREAD

**Issue by akesson** [leptos-rs/cargo-leptos#52]
Today the same release, dev and test profiles are used both for the front and server. 

`cargo-leptos` should be able to set the profiles to use for front and server independently for release, dev and test.

This implies more configuration options:

```toml
[[workspace.metadata.leptos]]
front-dev-profile = "myprofile"
front-release-profile = "myprofile"
front-test-profile = "myprofile"

server-dev-profile = "myprofile"
server-release-profile = "myprofile"
server-test-profile = "myprofile"
```
